-- ============================================================
-- Migration 005: Individual Evaluation Sheet (Annex G)
-- ============================================================

CREATE TABLE IF NOT EXISTS `ies_weight_templates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position_category` ENUM('teaching_related','non_teaching','teacher_i') NOT NULL,
  `bracket_key` VARCHAR(50) DEFAULT NULL,
  `bracket_key_norm` VARCHAR(50) GENERATED ALWAYS AS (IFNULL(`bracket_key`, '__FLAT__')) STORED,
  `criteria_key` VARCHAR(60) NOT NULL,
  `max_points` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `display_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_iwt_category_bracket_criteria` (`position_category`,`bracket_key_norm`,`criteria_key`),
  KEY `idx_iwt_lookup` (`position_category`,`bracket_key`,`display_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ies_evaluations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `application_code` VARCHAR(50) NOT NULL,
  `applicant_id` INT NOT NULL,
  `vacancy_id` INT NOT NULL,
  `position_category` ENUM('teaching_related','non_teaching','teacher_i') NOT NULL,
  `bracket_key` VARCHAR(50) DEFAULT NULL,
  `job_group_sg_level` VARCHAR(20) DEFAULT NULL,
  `office` VARCHAR(150) DEFAULT NULL,
  `contact_number` VARCHAR(30) DEFAULT NULL,
  `evaluated_by` INT NOT NULL,
  `total_score` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  `attested_by_applicant_at` DATETIME DEFAULT NULL,
  `attested_by_chair_id` INT DEFAULT NULL,
  `attested_by_chair_at` DATETIME DEFAULT NULL,
  `status` ENUM('draft','submitted','attested') NOT NULL DEFAULT 'draft',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ies_application_code` (`application_code`),
  KEY `idx_ies_applicant` (`applicant_id`),
  KEY `idx_ies_vacancy` (`vacancy_id`),
  KEY `idx_ies_evaluated_by` (`evaluated_by`),
  KEY `idx_ies_chair` (`attested_by_chair_id`),
  CONSTRAINT `fk_ies_applicant` FOREIGN KEY (`applicant_id`) REFERENCES `applications` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ies_vacancy` FOREIGN KEY (`vacancy_id`) REFERENCES `vacancies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ies_evaluated_by` FOREIGN KEY (`evaluated_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_ies_chair` FOREIGN KEY (`attested_by_chair_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ies_criterion_scores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ies_evaluation_id` INT NOT NULL,
  `criteria_key` VARCHAR(60) NOT NULL,
  `weight_allocation` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `qualification_notes` TEXT DEFAULT NULL,
  `computation_notes` TEXT DEFAULT NULL,
  `actual_score` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_ics_eval_criteria` (`ies_evaluation_id`,`criteria_key`),
  CONSTRAINT `fk_ics_eval` FOREIGN KEY (`ies_evaluation_id`) REFERENCES `ies_evaluations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `ies_weight_templates` (`position_category`, `bracket_key`, `criteria_key`, `max_points`, `display_order`) VALUES
('teaching_related','SG_11_15','education',10,1),
('teaching_related','SG_11_15','training',10,2),
('teaching_related','SG_11_15','experience',10,3),
('teaching_related','SG_11_15','performance',20,4),
('teaching_related','SG_11_15','outstanding_accomplishments',10,5),
('teaching_related','SG_11_15','application_of_education',10,6),
('teaching_related','SG_11_15','application_of_ld',10,7),
('teaching_related','SG_11_15','potential',20,8),
('teaching_related','SG_16_23_27','education',10,1),
('teaching_related','SG_16_23_27','training',10,2),
('teaching_related','SG_16_23_27','experience',10,3),
('teaching_related','SG_16_23_27','performance',20,4),
('teaching_related','SG_16_23_27','outstanding_accomplishments',5,5),
('teaching_related','SG_16_23_27','application_of_education',15,6),
('teaching_related','SG_16_23_27','application_of_ld',10,7),
('teaching_related','SG_16_23_27','potential',20,8),
('teaching_related','SG_24_CHIEF','education',10,1),
('teaching_related','SG_24_CHIEF','training',10,2),
('teaching_related','SG_24_CHIEF','experience',10,3),
('teaching_related','SG_24_CHIEF','performance',25,4),
('teaching_related','SG_24_CHIEF','outstanding_accomplishments',10,5),
('teaching_related','SG_24_CHIEF','application_of_education',10,6),
('teaching_related','SG_24_CHIEF','application_of_ld',10,7),
('teaching_related','SG_24_CHIEF','potential',15,8),
('non_teaching','GENERAL_SERVICES','education',5,1),
('non_teaching','GENERAL_SERVICES','training',5,2),
('non_teaching','GENERAL_SERVICES','experience',20,3),
('non_teaching','GENERAL_SERVICES','performance',10,4),
('non_teaching','GENERAL_SERVICES','outstanding_accomplishments',5,5),
('non_teaching','GENERAL_SERVICES','application_of_education',0,6),
('non_teaching','GENERAL_SERVICES','application_of_ld',0,7),
('non_teaching','GENERAL_SERVICES','potential',55,8),
('non_teaching','SG_1_9_NON_GS','education',5,1),
('non_teaching','SG_1_9_NON_GS','training',5,2),
('non_teaching','SG_1_9_NON_GS','experience',15,3),
('non_teaching','SG_1_9_NON_GS','performance',20,4),
('non_teaching','SG_1_9_NON_GS','outstanding_accomplishments',10,5),
('non_teaching','SG_1_9_NON_GS','application_of_education',10,6),
('non_teaching','SG_1_9_NON_GS','application_of_ld',10,7),
('non_teaching','SG_1_9_NON_GS','potential',20,8),
('non_teaching','SG_10_22_27','education',5,1),
('non_teaching','SG_10_22_27','training',10,2),
('non_teaching','SG_10_22_27','experience',20,3),
('non_teaching','SG_10_22_27','performance',20,4),
('non_teaching','SG_10_22_27','outstanding_accomplishments',10,5),
('non_teaching','SG_10_22_27','application_of_education',10,6),
('non_teaching','SG_10_22_27','application_of_ld',10,7),
('non_teaching','SG_10_22_27','potential',20,8),
('non_teaching','SG_24_CHIEF','education',10,1),
('non_teaching','SG_24_CHIEF','training',5,2),
('non_teaching','SG_24_CHIEF','experience',15,3),
('non_teaching','SG_24_CHIEF','performance',20,4),
('non_teaching','SG_24_CHIEF','outstanding_accomplishments',10,5),
('non_teaching','SG_24_CHIEF','application_of_education',10,6),
('non_teaching','SG_24_CHIEF','application_of_ld',10,7),
('non_teaching','SG_24_CHIEF','potential',20,8),
('teacher_i',NULL,'education',10,1),
('teacher_i',NULL,'training',10,2),
('teacher_i',NULL,'experience',10,3),
('teacher_i',NULL,'pbet_let_lept_rating',10,4),
('teacher_i',NULL,'ppst_coi',35,5),
('teacher_i',NULL,'ppst_ncoi',25,6)
ON DUPLICATE KEY UPDATE
  `max_points` = VALUES(`max_points`),
  `display_order` = VALUES(`display_order`);
